### ISSUE TITLE
npm run dev throws SyntaxError

### ISSUE THREAD

**Issue by sammyjava** [amand1996/cross-intermine-search-tool#1]
```
shokin@morangie:~/cross-intermine-search-tool$ npm run dev

> cross-intermine-search-tool@1.0.0 dev /home/shokin/cross-intermine-search-tool
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

/home/shokin/cross-intermine-search-tool/build/webpack.base.conf.js:43
      ...(config.dev.useEslint ? [createLintingRule()] : []),
      ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/shokin/cross-intermine-search-tool/build/webpack.dev.conf.js:7:27)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

npm ERR! Linux 4.4.0-131-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! cross-intermine-search-tool@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cross-intermine-search-tool@1.0.0 dev script 'webpack-dev-server --inline --progress --config build/webpack.dev.conf.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cross-intermine-search-tool package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --inline --progress --config build/webpack.dev.conf.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cross-intermine-search-tool
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cross-intermine-search-tool
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/shokin/cross-intermine-search-tool/npm-debug.log
shokin@morangie:~/cross-intermine-search-tool$ npm --version
3.5.2
shokin@morangie:~/cross-intermine-search-tool$
```

**Comment by amand1996** [comment]
@sammyjava I m unable to reproduce this error. I hope you are running the dev branch as it has the latest code right now. It might be an issue with the npm version. I'm using npm v5.6.0 and nodejs v8.11.3. Can you try running the dev branch with the mentioned npm and node versions. Let me know if you face the issue again. (I really don't know why its not working for you)
